### ISSUE TITLE
🧪 Add Integration Tests with Claude Desktop

### ISSUE THREAD

**Issue by dietrichson** [chi2labs/mcpr#12]
## Overview

Create comprehensive integration tests that verify generated MCP servers work correctly with Claude Desktop and other MCP clients.

## Background

Unit tests aren't sufficient to ensure mcpr-generated servers work in practice. We need integration tests that:
1. Generate actual server packages
2. Install them locally
3. Test with real MCP clients
4. Verify all requirements are met (especially zero stderr)

### 1. Basic Functionality Tests

```r
test_that("generated server connects to Claude Desktop", {
  # Generate a test server
  temp_dir <- tempdir()
  server_dir <- file.path(temp_dir, "test-server")
  
  mcp_create_server(
    source = test_path("fixtures/simple_functions.R"),
    output_dir = server_dir,
    name = "test-server"
  )
  
  # Start server and test connection
  server_process <- start_test_server(server_dir)
  
  # Send initialize request
  response <- send_mcp_request(server_process, list(
    jsonrpc = "2.0",
    method = "initialize",
    params = list(protocolVersion = "0.1.0"),
    id = 1
  ))
  
  expect_equal(response, "test-server")
  
  stop_test_server(server_process)
})
```

### 2. Stderr Compliance Tests

```r
test_that("server produces zero stderr output", {
  # Create server that loads packages with startup messages
  test_code <- '
  library(ggplot2)  # Known to produce startup messages
  
  #* @mcp_tool
  plot_data <- function(x, y) {
    plot(x, y)
  }
  '
  
  server_dir <- generate_test_server(test_code)
  monitor <- start_stderr_monitor(server_dir)
  
  # Run various operations
  run_server_operations(server_dir)
  
  # Verify absolutely no stderr output
  expect_equal(monitor(), "")
})
```

### 3. Error Handling Tests

```r
test_that("R errors don't leak to stderr", {
  test_code <- '
  #* @mcp_tool
  failing_function <- function() {
    stop("This is an intentional error")
  }
  '
  
  server_dir <- generate_test_server(test_code)
  response <- call_mcp_tool(server_dir, "failing_function")
  
  # Error should be in response, not stderr
  expect_true("error" %in% names(response))
  expect_match(response, "intentional error")
})
```

### 4. Performance Tests

```r
test_that("server handles large data efficiently", {
  test_code <- '
  #* @mcp_tool
  process_large_data <- function(n = 1000000) {
    data.frame(x = rnorm(n), y = rnorm(n))
  }
  '
  
  server_dir <- generate_test_server(test_code)
  
  timing <- system.time({
    response <- call_mcp_tool(server_dir, "process_large_data")
  })
  
  expect_lt(timing[["elapsed"]], 5)  # Should complete in < 5 seconds
})
```

### 5. Cross-Platform Tests

- Test on Windows, macOS, and Linux
- Verify path handling works correctly
- Test with different R versions
- Test with different Node.js versions

### 6. Claude Desktop Specific Tests

```yaml
# .github/workflows/claude-desktop-test.yml
name: Claude Desktop Integration Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r-version: ['4.3', '4.4']
        node-version: ['18.x', '20.x']
    
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: actions/setup-node@v3
      
      - name: Install mcpr
        run: |
          R CMD INSTALL .
      
      - name: Run integration tests
        run: |
          Rscript tests/integration/run-all.R
```

### Test Utilities Package
```r
# R/test-utils.R
start_test_server <- function(server_dir) {
  # Start server and return process handle
}

send_mcp_request <- function(process, request) {
  # Send JSON-RPC request and get response
}

monitor_stderr <- function(process) {
  # Monitor stderr output during tests
}
```

### Mock MCP Client
- Implement minimal MCP client for testing
- Support all standard MCP operations
- Verify protocol compliance

## Success Criteria
- All generated servers pass integration tests
- Zero stderr output in all scenarios
- Works on all major platforms
- Performance meets requirements
- Clear error reporting for failures

## CI/CD Integration
- Run on every PR
- Test matrix for multiple platforms/versions
- Performance benchmarks tracked over time
- Automated Claude Desktop compatibility check

## Priority
**MEDIUM-HIGH** - Important for quality assurance and user confidence
