### ISSUE TITLE
🧪 Create Comprehensive Test Suite for mcpR

### ISSUE THREAD

**Issue by dietrichson** [chi2labs/mcpr#7]
## Description
Develop a comprehensive test suite for the mcpR package to ensure reliability, correctness, and compliance with the MCP specification.

### 1. Decorator Parsing Tests
- [ ] Parse various decorator syntaxes
- [ ] Handle malformed decorators gracefully
- [ ] Test parameter type inference
- [ ] Validate decorator combinations
- [ ] Test multiline descriptions

### 2. Protocol Compliance Tests
- [ ] JSON-RPC 2.0 message format validation
- [ ] MCP message type handling (initialize, tools/list, etc.)
- [ ] Protocol version negotiation
- [ ] Capability advertisement
- [ ] Error response formatting

### 3. Type Conversion Tests
- [ ] Basic R types to JSON conversion
- [ ] Complex objects (data.frames, lists, S3/S4)
- [ ] Special values (NA, NULL, Inf, NaN)
- [ ] Large object handling
- [ ] Round-trip conversion accuracy
- [ ] Custom serializer registration

### 4. Transport Layer Tests
- [ ] stdio communication (primary)
- [ ] Message boundary detection
- [ ] Large message handling
- [ ] Connection lifecycle
- [ ] Error recovery

### 5. Integration Tests
- [ ] End-to-end function exposure
- [ ] Multiple function registration
- [ ] Concurrent request handling
- [ ] Resource subscription
- [ ] Real-world usage patterns

### 6. Performance Tests
- [ ] Function call overhead
- [ ] Large data serialization
- [ ] Memory usage profiling
- [ ] Concurrent request handling
- [ ] Stress testing limits

### 7. Security Tests
- [ ] Input validation
- [ ] Prevent code injection
- [ ] Safe error messages
- [ ] Resource access controls

### Mock Components
```r
# Mock MCP client for testing
MockMCPClient <- R6::R6Class("MockMCPClient",
  public = list(
    send = function(method, params = NULL) {
      # Send request and capture response
    },
    
    expect_response = function(expected) {
      # Validate response matches expected
    }
  )
)
```

### Test Helpers
```r
# Helper to create test functions with decorators
create_test_function <- function(decorators, body) {
  # Dynamic function creation for testing
}

# Helper to validate JSON schemas
validate_schema <- function(object, schema) {
  # JSON schema validation
}
```

### Example Test
```r
test_that("decorator parsing works correctly", {
  code <- '
    #* @mcp_tool
    #* @description Calculate sum
    #* @param x [numeric] First number
    #* @param y [numeric] Second number
    #* @returns Sum of x and y
    add <- function(x, y) { x + y }
  '
  
  parsed <- parse_decorators(code)
  
  expect_equal(parsed$functions$add$type, "tool")
  expect_equal(parsed$functions$add$description, "Calculate sum")
  expect_equal(parsed$functions$add$params$x$type, "numeric")
})
```

### GitHub Actions Workflow
```yaml
name: R-CMD-check

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        r-version: ['4.0', '4.1', '4.2', '4.3']
    
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
    
    - name: Install dependencies
      run: |
        install.packages("remotes")
        remotes::install_deps(dependencies = TRUE)
    
    - name: Run tests
      run: |
        devtools::test()
    
    - name: Check coverage
      run: |
        covr::codecov()
```

### Coverage Requirements
- Minimum 90% code coverage
- 100% coverage for core protocol handling
- All error paths must be tested
- All decorator types must be tested

### Test Organization
```
tests/
├── testthat/
│   ├── test-decorators.R
│   ├── test-protocol.R
│   ├── test-transport.R
│   ├── test-types.R
│   ├── test-integration.R
│   └── test-security.R
└── fixtures/
    ├── example_functions.R
    ├── mock_responses.json
    └── test_data.rds
```

### Documentation
- [ ] Test plan document
- [ ] Testing best practices guide
- [ ] Contribution testing requirements
- [ ] Performance baselines

### Cross-Platform Testing
- Windows line endings (CRLF)
- Path separators
- Process handling differences
- Character encoding

### R Version Compatibility
- Test on R 4.0+
- Handle version-specific features
- Graceful degradation

### Claude Desktop Testing
- [ ] Create test configuration
- [ ] Automated integration tests
- [ ] Example test scenarios
- [ ] Performance benchmarks
